### ISSUE TITLE
Pin clash welcome message on create lobby 

### ISSUE THREAD

**Issue by CrownBerry** [Cuttlerat/yoba#142]
_Given_ User want to create CoC lobby
_When_ User type `/clash@botname`
_Then_:
**Expected** Bot replay with message containing a link to CoC-lobby AND pin this message in group
**Actual** Bot replay with message containing a link to CoC-lobby

**Comment by Cuttlerat** [comment]
I'll close all Issues with this stupid template, just describe the problem in a human language
